#!/usr/bin/perl

use lib '/home/wicker/data/WICKERsoft/';
use Biomodule;
use GD;
#use GD::SVG;

if (@ARGV < 4) {
	print "1.= .blast_plot\n";
	print "2.= minimal identity\n";
	print "3.= anno table for seq1 (if not available, just type n)\n";
	print "4.= anno table for seq2 (if not available, just type n)\n";
	print "5.= width of image (otional, default = 550)\n";
	exit;
	}

$min_sim = $ARGV[1];
$out_name = $ARGV[0];
$out_name =~ s/blast_plot/png/;

$wide = 500;
if ($ARGV[4]) {
	$wide = $ARGV[4];
	}

$font_class = "GD::SVG::Font";

# get all info from blast plot file
open(IN,"$ARGV[0]");
while (<IN>) {

	($nam,$l) = /INFILE_1\s+(\S+)\s+(\S+)\s/;
	if ($nam) {
		$name1 = $nam;
		$len1 = $l;
		}

        ($nam,$l) = /INFILE_2\s+(\S+)\s+(\S+)\s/;
        if ($nam) {
                $name2 = $nam;
                $len2 = $l;
                }
	
	($be1,$en1,$be2,$en2,$sim) = /^(\d+)-(\d+)\s+(\d+)-(\d+)\s+([\d\.]+)%/;
	if ($en1) {
		if ($sim >= $min_sim) {
		$data[$count][0] = $be1;
		$data[$count][1] = $en1;
		$data[$count][2] = $be2;
		$data[$count][3] = $en2;
		$data[$count][4] = $sim;
		$count++;
		}
		}

	}
close(IN);

# get info from annotation tables
$anno = $ARGV[2];
$seq_id = 1;
$count_ann=0;
&get_anno;

$anno = $ARGV[3];
$seq_id = 2;
&get_anno;


sub get_anno {
open(IN,"$anno");
while (<IN>) {

        ($be,$en,$id,$or,$cl,$rem,$lev) = /^(\d+)-(\d+)\s+([^;]+);([^;]+);([^;]+);([^;]*)(;.*)/;
        if ($en) {
		$lev =~ s/;//;
		if ($lev eq '') {
			$lev =0;
			}
		$anno[$count_ann][0] = $seq_id;
                $anno[$count_ann][1] = $be;
                $anno[$count_ann][2] = $en;
                $anno[$count_ann][3] = $id;
                $anno[$count_ann][4] = $or;
                $anno[$count_ann][5] = $lev;
		$anno[$count_ann][6] = $rem;
                $count_ann++;
		print "$count_ann\t$seq_id\t$be,$en,$id,$or,$cl,$lev\n";
                }

        }
close(IN);
}






# calculate x-zoom factor and image height
$zoom = $len1/$wide;
$high = int($len2/$zoom);

$x_base = 150;
$y_base = 150;

print "$wide x $high\n";

# create a new image
$img_x = $wide +1.8*$x_base;
$img_y = $high +1.2*$y_base;
$img = new GD::Image($img_x,$img_y);

# allocate some colors
$white = $img->colorAllocate(255,255,255);
$black = $img->colorAllocate(0,0,0);       
$red = $img->colorAllocate(255,0,0);      
$blue = $img->colorAllocate(0,0,255);

# make red gradient and color legend
@red = ();
$count_col =0;
%red = ();
$col_step = (100-$min_sim)/25;
print "col step = $col_step\n";
$time = 5;

$x1 = $x_base+$wide+20;
$y1 = $y_base+10;
$lab = "Identity";
$img->string(gdLargeFont,$x1,$y1,$lab,$black);
#$img->string($font_class->Small,$x1,$y1,$lab,$black);

for($i=0;$i<=255;$i+=10) {
        $r = $i;
        $g = 0;
        $b = 0;
        $name = "red$count_col";
        $col = $img->colorAllocate($r,$g,$b);
        $red{$name} = $col;

        $fill = $red{$name};

	$sim = (int(($min_sim+$count_col*$col_step)*10))/10;

	$x1 = $x_base+$wide+20;
	$x2 = $x1+15;
	$x3 = $x1+25;
	$y1 = $y_base+$count_col*4+30;
	$y2 = $y1+7;

	$img->filledRectangle($x1,$y1,$x2,$y2,$fill);

	if ($time > 4) {
		$val = sprintf("%.1f",$sim);
		$lab = "$val %";
		$img->string(gdSmallFont,$x3,$y1,$lab,$black);
		$time =0;
		}
	$time ++;

	$count_col++;

	print "$i\t$name\t$r,$g,$b\t$sim\t$x1,$y1,$x2,$y2\n";

        }






# draw frame for dotplot
$x1 = $x_base;
$x2 = $x_base+$wide;
$y1 = $y_base;
$y2 = $y_base+$high; 
$img->rectangle($x1,$y1,$x2,$y2,$black);

# draw labels
$midx = int($wide/2);
$midy = int($high/2);
$img->string(gdLargeFont,$x_base,10,$name1,$black);
$img->stringUp(gdLargeFont,10,$high,$name2,$black);

# determine order of magnitude to set scale step
$log = log($len1)/log(10);
$pot = (int($log))-1;
$step = 10**$pot;
print "log = $log\t==> step = $step\n";

@len = qw(100000 200000 500000 1000000);
@ste = qw(20000  50000  100000  200000);

$step = 10000;
for($i=0;$i<@len;$i++) {
	$l = $len[$i];
	print "$l => $ste[$i]\n";
	if ($len1 > $l) {
		$step = $ste[$i];
		print "step: $len\t$l\t==> $step\n";
		}
	}

# draw x scale
#$step = int($len1/10);
for($i=0;$i<=$len1;$i+=$step) {
	$x1 = $x_base+int($i/$zoom);
	$y1 = $y_base;
	$y2 = $y_base-3;
	$val = $i;
	if ($val > 1000) {
		$val = int($i/1000);
		}
	$img->line($x1,$y1,$x1,$y2,$black);
	$img->string(gdSmallFont,$x1,$y_base-17,$val,$black);
	}

# draw y scale
for($i=0;$i<=$len2;$i+=$step) {
        $y1 = $y_base+int($i/$zoom);
        $x1 = $x_base;
        $x2 = $x_base-3;
	$val = $i;
        if ($val > 1000) {
                $val = int($i/1000);
                }
        $img->line($x1,$y1,$x2,$y1,$black);
        $img->stringUp(gdSmallFont,$x_base-17,$y1,$val,$black);
        }


# loop through blast hits and draw lines
for($i=0;$i<$count;$i++) {

	$x1 = $x_base+int($data[$i][0]/$zoom);
	$x2 = $x_base+int($data[$i][1]/$zoom);
	$y1 = $y_base+int($data[$i][2]/$zoom);
	$y2 = $y_base+int($data[$i][3]/$zoom);

	# make heat code
	$sim = $data[$i][4];
	$diff = $sim-$min_sim;
	$col_step = 25/(100-$min_sim);
	$val = int($diff*$col_step);
	$col = "red$val";
	$fill = $red{$col};
	#print "$sim\t$diff\t==>\t$val\t$col\n";
	#$delta = (100-$sim*5);
	#$fill = $img->colorAllocate($delta,0,0);

	if ($sim > 99) {
		$col = "red0";
	#	$fill = $red{$col};
		}
	#$fill = $black;

	#$img->setThickness(2);
	$img->line($x1,$y1,$x2,$y2,$fill);
	}


# draw annotation
$x2_old = 0;
for($i=0;$i<$count_ann;$i++) {

	$id = $anno[$i][3];
	print "$anno[$i][0]\t$anno[$i][1]\t$anno[$i][2]\t$anno[$i][3]\n";
	# flag pseudogenes
	$rem = $anno[$i][6];
	$fill = $black;
	if ($rem =~ /pseudo/) {
		$fill = $red;
		};

	$symbol = ">";
	if($anno[$i][4] eq 'rev') {
		$symbol = "<";
		}	

	# annotation sequence horizontal	
        if ($anno[$i][0] ==1){

		$fill = $black;
                if ($id =~ /TE/) {
                        $fill = $red;
                        }
		$id =~ s/^TE_//;

                # make box for gene
                $x1 = $x_base+int($anno[$i][1]/$zoom);
		$x2 = $x_base+int($anno[$i][2]/$zoom)+1;

		# space if genes are too close
		$delta = $x1-$x2_old;
		if ($delta <10) {
			$x1+=10;
			$x2+=10;
			}
		$x2_old = $x2;

                $y1 = $y_base-25;
                $y2 = $y1+7;
                $img->filledRectangle($x1,$y1,$x2,$y2,$fill);

		# make gene label
		$y1 = $y_base-40;
                $y2 = $y_base-45;
                $img->string(gdSmallFont,$x1,$y1,$symbol,$black);
                $img->stringUp(gdSmallFont,$x1,$y2,$id,$fill);


                }

	# annotation sequence vertical
        if ($anno[$i][0] ==2){
                $y1 = $y_base+int($anno[$i][1]/$zoom);
		$y2 = $y1-7;
		$y2 = $y_base+int($anno[$i][2]/$zoom);
                $delta = abs($y2-$y_old);
                if ($delta <11) {
			#        $y2 = $y_old +11;
                        }
                $y_old = $y2;


                $x1 = $x_base-40;
                $x2 = $x_base-(length($id)*5)-50;
		#$img->stringUp(gdSmallFont,$x1,$y1,$symbol,$black);
		$img->string(gdSmallFont,$x2,$y2,$id,$fill);

		# make box for gene
		$y1 = $y_base+int($anno[$i][1]/$zoom);
		$y2 = $y1-2;
		$y2 = $y_base+int($anno[$i][2]/$zoom)+2;
		$x1 = $x_base-25;
		$x2 = $x1+7;
		$img->filledRectangle($x1,$y1,$x2,$y2,$fill);

                }


        }

	



# convert into png data
$out = "img.png";
$out = $out_name;
open $png, '>', $out or die;
binmode $png;
print $png $img->png;

# open image
print "opening image, please wait\n";

`eog $out`;

print "wrote $out\n";






























